### ISSUE TITLE
Enlarge LCD mounting holes on ezLCD-5035

### ISSUE THREAD

**Issue by microlan** [earthlcd/ezLCD-5x#43]
See Randy for details

**Comment by randy-earthlcd** [comment]
hmm think this was supposed to be ezLCD-5035!

**Comment by microlan** [comment]
Yeah I believe it was.  Will call to discuss the proper size (I don't seem to have notes as to what size we came up with)

**Comment by microlan** [comment]
Fixed in 5035 Rev B
