### ISSUE TITLE
ez.SerialTx parameter order error

### ISSUE THREAD

**Issue by JacobChrist** [earthlcd/ezLCD-5x#68]
**Describe the issue**
A clear and concise description of what the issue is.

The rs485.lua example has this code:

	--  ez.SerialTx(Data, MaxLen, PortNo)
		ez.SerialTx(ez.SerialNo, 24, 1)

The ezLCD Lua Application Programming Interface (Section 30.4 p. 128) describes the ez.SerialTx() as such:

ez.SerialTx(Data [, PortNo [, MaxLen ]])

One of the two is incorrect.  Randy says that the rs485.lua is working code, if so then the documentation is in error.

**Comment by microlan** [comment]
MaxLen and PortNo are reversed in the docs.  PortNo should be the last param.  Fixed in docs updated on or after 3/29/23.
