### ISSUE TITLE
Lua commands to load bitmap files do not work if the file is jpeg format

### ISSUE THREAD

**Issue by JacobChrist** [earthlcd/ezLCD-5x#69]
**Describe the bug**
Lua commands to load bitmap files do not work if the file is jpeg format.

Tested with both ez.PutPicNo() and ez.PutPictFile().

Also tested trying to load bmp file (which seem to work fine with both functions.

**To Reproduce**
``` Lua
    ez.PutPictFile(0, 0, "Images/EarthLCD_320x240_Splash.jpeg") -- doesn't work
    ez.PutPictFile(0, 0, "/Images/EarthLCD_320x240_Splash.jpeg") -- doesn't work
    ez.PutPictFile(0, 0, "Images/EarthLCD_320x240_Splash.bmp")	-- works
    ez.PutPictFile(0, 0, "/Images/EarthLCD_320x240_Splash.bmp") -- works
```

**Comment by JacobChrist** [comment]
Here is the firmware version I'm using for the 5035:
Ver: 3.0.0  Mar 29 2023 (NoSPI)
Lua 5.3.5
S/N: 2c0022000751393334383939
320x240

I confirmed that the gas guage jpg's are working in my autoexec.lua example as well. So it appears that some jpg's render but not others.

Here is my image (jpg) which does not render:
![pulltest-bg](https://user-images.githubusercontent.com/198251/229549486-f01fdd27-c8ad-4bda-a6ce-3a47c1d5376b.jpg)

Here is my bmp & jpg zipped up:
[pulltest-bg.zip](https://github.com/earthlcd/ezLCD-5x/files/11139618/pulltest-bg.zip)

My bmp does render but it doesn't display how I would expect it to.  As you can see the image is offset to the right (and appears to wrap around).  
![image](https://user-images.githubusercontent.com/198251/229550520-f1fb45ba-efce-413e-8ad5-3a277bff9c93.png)

The image was generated by opening the jpg in gimp then exporting as a bmp with these settings.
![image](https://user-images.githubusercontent.com/198251/229550954-e01e019a-138a-447d-a45f-4ec552506bfb.png)

**Comment by JacobChrist** [comment]
At the suggestion Randy tried the following (no X,Y):

``` Lua
	local result = ez.PutPictFile("/Images/EarthLCD_320x240_Splash.jpeg")
	ez.SerialTx("result=".. tostring(result) .. "\r\n", 80, debug_port)
```

Serial output: result=false

**Comment by microlan** [comment]
I suspect this issue may be related to the specific internal JPG format of the file you chose.  We have found that the hardware JPEG decoder doesn't seem to work with certain JPG file formats (not really sure why).

**Comment by JacobChrist** [comment]
Doing more testing on this tonight and jpeg's written from GIMP are still an issue.

**Comment by JacobChrist** [comment]
Addressed in commit: https://github.com/earthlcd/EZLCD-5xxx-Master/commit/a8ee9e0cce128bca59d7cdbf2892b06de01db48e but not yet released.

**Comment by JacobChrist** [comment]
Addressed (again) in commit: https://github.com/earthlcd/EZLCD-5xxx-Master/commit/5087ce949399b93036bdf4747b2ef4c6c871a00d and master advanced.

**Comment by JacobChrist** [comment]
@microlan I've pushed this fix to master and I'm closing.
